var trains = {
    swallow: {
        name: 'Swallow',
        speed: 60,
        acc: 9,
        wagons: 3,
        reliability: 60,
        price: 15000,
    },
    raven: {
        name: 'Raven',
        speed: 85,
        acc: 2,
        wagons: 4,
        reliability: 50,
        price: 35000,
    },
    rhino: {
        name: 'Rhinoceros',
        speed: 70,
        acc: 18,
        wagons: 4,
        reliability: 70,
        price: 70000,
    },
    donkey: {
        name: 'Donkey',
        speed: 60,
        acc: 2,
        wagons: 7,
        reliability: 40,
        price: 100000,
    },
    falcon: {
        name: 'Falcon',
        speed: 160,
        acc: 19,
        wagons: 4,
        reliability: 60,
        price: 135000,
    },
    mole: {
        name: 'Mole',
        speed: 120,
        acc: 10,
        wagons: 5,
        reliability: 80,
        price: 150000,
    },
    kite: {
        name: 'Red Kite',
        speed: 100,
        acc: 6,
        wagons: 6,
        reliability: 95,
        price: 0,
    },
    bat: {
        name: 'Bat',
        speed: 95,
        acc: 13,
        wagons: 6,
        reliability: 50,
        price: 165000,
    },
    panther: {
        name: 'Panther',
        speed: 180,
        acc: 3,
        wagons: 5,
        reliability: 85,
        price: 175000,
    },
    bear: {
        name: 'Black bear',
        speed: 75,
        acc: 13,
        wagons: 8,
        reliability: 60,
        price: 200000,
    },
    lynx: {
        name: 'Lynx',
        speed: 160,
        acc: 17,
        wagons: 5,
        reliability: 80,
        price: 150000,
    },
    boar: {
        name: 'Boar',
        speed: 130,
        acc: 11,
        wagons: 6,
        reliability: 50,
        price: 225000,
    },
    elephant: {
        name: 'Elephant',
        speed: 65,
        acc: 3,
        wagons: 11,
        reliability: 40,
        price: 300000,
    },
    bull: {
        name: 'Bull',
        speed: 110,
        acc: 5,
        wagons: 7,
        reliability: 90,
        price: 0,
    },
    odin: {
        name: 'Odin',
        speed: 130,
        acc: 10,
        wagons: 6,
        reliability: 80,
        price: 275000,
    },
    dionysos: {
        name: 'Dionysos',
        speed: 150,
        acc: 18,
        wagons: 5,
        reliability: 95,
        price: 200000,
    },
    heracles: {
        name: 'Heracles',
        speed: 85,
        acc: 1,
        wagons: 10,
        reliability: 80,
        price: 350000,
    },
    prometheus: {
        name: 'Prometheus',
        speed: 100,
        acc: 4,
        wagons: 8,
        reliability: 75,
        price: 375000,
    },
    morpheus: {
        name: 'Morpheus',
        speed: 200,
        acc: 5,
        wagons: 13,
        reliability: 80,
        price: 1000000,
        slots: 2,
    },
    osiris: {
        name: 'Osiris',
        speed: 120,
        acc: 7,
        wagons: 7,
        reliability: 90,
        price: 500000,
    },
    apollo: {
        name: 'Apollo',
        speed: 100,
        acc: 6,
        wagons: 9,
        reliability: 70,
        price: 500000,
    },
    ares: {
        name: 'Ares',
        speed: 160,
        acc: 19,
        wagons: 6,
        reliability: 90,
        price: 600000,
    },
    neptune: {
        name: 'Neptune',
        speed: 120,
        acc: 22,
        wagons: 8,
        reliability: 80,
        price: 300000,
    },
    horus: {
        name: 'Horus',
        speed: 110,
        acc: 4,
        wagons: 10,
        reliability: 70,
        price: 750000,
    },
    thor: {
        name: 'Thor',
        speed: 150,
        acc: 15,
        wagons: 8,
        reliability: 75,
        price: 600000,
    },
    poseidon: {
        name: 'Poseidon',
        speed: 220,
        acc: 12,
        wagons: 22,
        reliability: 80,
        price: 2000000,
        slots: 3,
    },
    
    
    unicorn: {
        name: 'Unicorn',
        speed: 115,
        acc: 2,
        wagons: 12,
        reliability: 60,
        price: 800000,
    },
    medusa: {
        name: 'Medusa',
        speed: 250,
        acc: 20,
        wagons: 6,
        reliability: 95,
        price: 900000,
    },
    basilisk: {
        name: 'Basilisk',
        speed: 170,
        acc: 6,
        wagons: 9,
        reliability: 75,
        price: 1000000,
    },
    satyr: {
        name: 'Satyr',
        speed: 200,
        acc: 2,
        wagons: 11,
        reliability: 85,
        price: 1100000,
    },
    leviathan: {
        name: 'Leviathan',
        speed: 120,
        acc: 20,
        wagons: 10,
        reliability: 95,
        price: 1200000,
    },
    centaur: {
        name: 'Centaur',
        speed: 190,
        acc: 15,
        wagons: 36,
        reliability: 80,
        price: 5000000,
        slots:4,
    },
};
