var trains = {
    swallow: {
        name: 'Swallow',
        speed: 60,
        acc: 9,
        wagons: 3,
        reliability: 60,
        price: 15000,
        service: 0,
    },
    raven: {
        name: 'Raven',
        speed: 85,
        acc: 2,
        wagons: 4,
        reliability: 50,
        price: 35000,
        service: 0,
    },
    rhino: {
        name: 'Rhinoceros',
        speed: 70,
        acc: 18,
        wagons: 4,
        reliability: 70,
        price: 70000,
        service: 0,
    },
    donkey: {
        name: 'Donkey',
        speed: 60,
        acc: 2,
        wagons: 7,
        reliability: 40,
        price: 100000,
        service: 0,
    },
    falcon: {
        name: 'Falcon',
        speed: 160,
        acc: 19,
        wagons: 4,
        reliability: 60,
        price: 135000,
        service: 0,
    },
    mole: {
        name: 'Mole',
        speed: 120,
        acc: 10,
        wagons: 5,
        reliability: 80,
        price: 150000,
        service: 0,
    },
    kite: {
        name: 'Red Kite',
        speed: 100,
        acc: 6,
        wagons: 6,
        reliability: 95,
        price: 0,
        service: 0,
    },
    bat: {
        name: 'Bat',
        speed: 95,
        acc: 13,
        wagons: 6,
        reliability: 50,
        price: 165000,
        service: 0,
    },
    panther: {
        name: 'Panther',
        speed: 180,
        acc: 3,
        wagons: 5,
        reliability: 85,
        price: 175000,
        service: 0,
    },
    bear: {
        name: 'Black bear',
        speed: 75,
        acc: 13,
        wagons: 8,
        reliability: 60,
        price: 200000,
        service: 0,
    },
    lynx: {
        name: 'Lynx',
        speed: 160,
        acc: 17,
        wagons: 5,
        reliability: 80,
        price: 150000,
        service: 0,
    },
    boar: {
        name: 'Boar',
        speed: 130,
        acc: 11,
        wagons: 6,
        reliability: 50,
        price: 225000,
        service: 0,
    },
    elephant: {
        name: 'Elephant',
        speed: 65,
        acc: 3,
        wagons: 11,
        reliability: 40,
        price: 300000,
        service: 0,
    },
    bull: {
        name: 'Bull',
        speed: 110,
        acc: 5,
        wagons: 7,
        reliability: 90,
        price: 0,
        service: 0,
    },
    odin: {
        name: 'Odin',
        speed: 130,
        acc: 10,
        wagons: 6,
        reliability: 80,
        price: 275000,
        service: 0,
    },
    dionysos: {
        name: 'Dionysos',
        speed: 150,
        acc: 18,
        wagons: 5,
        reliability: 95,
        price: 200000,
        service: 0,
    },
    heracles: {
        name: 'Heracles',
        speed: 85,
        acc: 1,
        wagons: 10,
        reliability: 80,
        price: 350000,
        service: 0,
    },
    prometheus: {
        name: 'Prometheus',
        speed: 100,
        acc: 4,
        wagons: 8,
        reliability: 75,
        price: 375000,
        service: 0,
    },
    morpheus: {
        name: 'Morpheus',
        speed: 200,
        acc: 5,
        wagons: 13,
        reliability: 80,
        price: 1000000,
        service: 0,
    },
    osiris: {
        name: 'Osiris',
        speed: 120,
        acc: 7,
        wagons: 7,
        reliability: 90,
        price: 500000,
        service: 0,
    },
};
